package uw.star.rts.analysis;

import uw.star.rts.analysis.BasicBlockFactory;
import uw.star.rts.artifact.*;
import uw.star.rts.extraction.*;
import junit.framework.TestCase;
import org.apache.bcel.classfile.*;

import edu.umd.cs.findbugs.ba.*;

import java.util.*;

/**
 * The class <code>BasicBlockFactoryTest</code> contains tests for the class
 * {@link <code>BasicBlockFactory</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 1/25/12 1:25 PM
 *
 * @author wliu
 *
 * @version $Revision$
 */
public class BasicBlockFactoryTest extends TestCase {
	
	String appname = "apache-xml-security";
	Application testapp;
	
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public BasicBlockFactoryTest(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		// Add additional set up code here
		  SIRJavaFactory sir = new SIRJavaFactory();
		  sir.setExperimentRoot("/home/wliu/sir");
		  testapp = sir.extract(appname);
	}

	/**
	 * Run the void parse() method test
	 */
	public void testParse() {
		Program p = testapp.getProgram(ProgramVariant.orig, 0);
		List<BasicBlock> bb = new BasicBlockFactory(p).parse();
		for(BasicBlock b: bb){
			//System.out.println(b);

		}
		
		assertTrue(true);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = parse()
 * package = uw.star.sts.analysis
 * package.sourceFolder = STS/test
 * superclassType = junit.framework.TestCase
 * testCase = BasicBlockFactoryTest
 * testClassType = uw.star.sts.analysis.BasicBlockFactory
 */